project:
  type: book
  output-dir: _book

execute:
  freeze: auto
  timeout: 600

book:
  title: "PyData Johannesburg Community Handbook"
  author: "Luis de Sousa"  
  reader-mode: true

  page-footer:
    left: |
      PyData Johannesburg Community Handbook by Luis de Sousa.

  cover-image: images/cover.png
  favicon: images/cover.png
  site-url: https://pydata-johannesburg.github.io
  repo-url: https://github.com/pydata-johannesburg/community-handbook
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd

format:
  html:
    theme:
      - cosmo
    code-link: true
    author-meta: "Luis de Sousa"
    callout-appearance: simple
    mermaid:
      theme: neutral

editor: source
